name: Build Webcamoid Portable EXE

on:
  # هذا يسمح لك بتشغيل العملية يدوياً من صفحة Actions
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout code (جلب الكود من GitHub)
      uses: actions/checkout@v4

    - name: 2. Unzip Source Code & Move (فك الضغط ونقل الملفات)
      # هذا يحل مشكلة المسارات الناتجة عن اسم الملف الطويل
      run: |
        # نفك ضغط الملف المرفوع. (تأكد من اسم الملف: "webcamoid-9.3.0 (1).zip")
        7z x "webcamoid-9.3.0 (1).zip" -oD extracted_source
        
        # ننقل المحتويات إلى مجلد مصدر موحد اسمه 'source'
        Move-Item extracted_source\* source -Force

    - name: 3. Set Source Directory Variable (تحديد مجلد الكود)
      run: echo "SOURCE_DIR=source" >> $GITHUB_ENV 

    - name: 4. Setup Qt environment (تثبيت مكتبات Qt)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        target: 'desktop'
        host: 'windows'
        arch: 'win64_msvc2019_64'
        
    - name: 5. Configure Build with CMake (إعداد البناء)
      # تم كتابة الأمر في سطر واحد لحل مشكلة PowerShell
      run: cmake -B build -S ${{ env.SOURCE_DIR }} -DCMAKE_BUILD_TYPE=Release
        
    - name: 6. Build the Webcamoid Project (بدء الكومبايل)
      run: cmake --build build --config Release
      
    - name: 7. Deploy/Package the Application (تجميع الملفات النهائية)
      run: |
        mkdir Webcamoid_Portable_9_3_0
        copy build\release\webcamoid.exe Webcamoid_Portable_9_3_0\webcamoid.exe
        
        # يستخدم windeployqt لتضمين جميع مكتبات Qt الضرورية
        $QT_ROOT\bin\windeployqt.exe Webcamoid_Portable_9_3_0\webcamoid.exe

    - name: 8. Upload Artifact (رفع الملف التنفيذي النهائي)
      # رفع المجلد كاملاً كملف ZIP
      uses: actions/upload-artifact@v4
      with:
        name: Webcamoid-Portable-EXE
        path: Webcamoid_Portable_9_3_0/
