name: Compile Webcamoid for Windows (Installer)

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: 1. Checkout code (جلب الكود من GitHub)
      uses: actions/checkout@v4

    - name: 2. Unzip Source Code & Move (فك الضغط ونقل الملفات)
      # هذا يحل مشكلة المسارات الناتجة عن اسم الملف الطويل
      run: |
        # نفك ضغط الملف المرفوع.
        7z x "webcamoid-9.3.0 (1).zip" -oD extracted_source
        
        # ننقل المحتويات إلى مجلد مصدر موحد اسمه 'source'
        Move-Item extracted_source\* source -Force

    - name: 3. Set Source Directory Variable (تحديد مجلد الكود)
      run: echo "SOURCE_DIR=source" >> $GITHUB_ENV 

    - name: 4. Setup Qt environment (تثبيت مكتبات Qt)
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        target: 'desktop'
        host: 'windows'
        arch: 'win64_msvc2019_64'
        
    - name: 5. Configure Build with CMake (إعداد البناء)
      run: cmake -B build -S ${{ env.SOURCE_DIR }} -DCMAKE_BUILD_TYPE=Release
        
    - name: 6. Build the Webcamoid Project (بدء الكومبايل)
      run: cmake --build build --config Release
      
    - name: 7. Deploy/Package the Application (تجميع الملفات لتغليفها)
      run: |
        mkdir out
        copy build\release\webcamoid.exe out\webcamoid.exe
        
        # يستخدم windeployqt لتضمين جميع مكتبات Qt الضرورية
        $QT_ROOT\bin\windeployqt.exe out\webcamoid.exe

    - name: 8. Setup Installer Builder (تجهيز أداة إنشاء ملف التثبيت)
      # **** تم استبدال Inno Setup بأداة WIX toolset المُتاحة ****
      uses: actions/setup-msbuild@v1 
      with:
        msbuild-architecture: x64
      # يتم تثبيت WiX Toolset تلقائيًا على سيرفرات ويندوز في GitHub

    - name: 9. Create MSI Installer Script (إنشاء ملف إعدادات التغليف)
      # إنشاء ملف (Product.wxs) لـ WiX Toolset
      run: |
        $ScriptContent = @"
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="*" Name="Webcamoid 9.3.0" Language="1033" Version="9.3.0" Manufacturer="Webcamoid Team" UpgradeCode="PUT-YOUR-OWN-GUID-HERE">
            <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
            <Media Id="1" Cabinet="media1.cab" EmbedCab="yes" />
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFilesFolder">
                <Directory Id="INSTALLFOLDER" Name="Webcamoid 9.3.0">
                  <Component Id="ProductComponent" Guid="*">
                    <File Id="WebcamoidExe" Name="webcamoid.exe" Source="out\webcamoid.exe" KeyPath="yes" Checksum="yes" />
                  </Component>
                </Directory>
              </Directory>
            </Directory>
            <Feature Id="ProductFeature" Title="Webcamoid 9.3.0" Level="1">
              <ComponentRef Id="ProductComponent" />
            </Feature>
          </Product>
        </Wix>
        "@
        Set-Content -Path "WebcamoidInstaller.wxs" -Value $ScriptContent
        
    - name: 10. Build MSI Installer (بناء ملف التثبيت MSI)
      # استخدام Candle و Light (أدوات WiX) لإنشاء ملف MSI
      run: |
        candle WebcamoidInstaller.wxs
        light -out WebcamoidSetup.msi WebcamoidInstaller.wixobj

    - name: 11. Upload Installer Artifact (رفع ملف التثبيت النهائي)
      # رفع ملف التثبيت MSI الذي تم إنشاؤه
      uses: actions/upload-artifact@v4
      with:
        name: Webcamoid-Installer-MSI
        path: WebcamoidSetup.msi
