# الخطوة 2: فك الضغط والنقل - يجب أن تكون كما يلي:
    - name: 2. Unzip Source Code & Move (فك الضغط ونقل الملفات)
      run: |
        # نفك ضغط الملف.
        7z x "webcamoid-9.3.0 (1).zip" -oD extracted_source
        
        # ننقل المحتويات إلى مجلد مصدر موحد اسمه 'source'
        Move-Item extracted_source\* source -Force

    # الخطوة 3: تحديد مجلد المصدر - يجب أن تكون كما يلي:
    - name: 3. Set Source Directory Variable (تحديد مجلد الكود)
      run: echo "SOURCE_DIR=source" >> $GITHUB_ENV 

    # ... (تجاهل الخطوة 4، يجب أن تكون صحيحة) ...

    # الخطوة 5: إعداد البناء - نكتبها في سطر واحد لتجنب خطأ PowerShell
    - name: 5. Configure Build with CMake (إعداد البناء)
      # نكتب الأمر بالكامل في سطر واحد لتجنب مشاكل علامة ^
      run: cmake -B build -S ${{ env.SOURCE_DIR }} -DCMAKE_BUILD_TYPE=Release
